services:
  techforb-challenge:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://db_app:3306/techforb_db?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USERNAME: root
      DB_PASSWORD: 1234
      FRONTEND_URL: http://localhost:4200
    restart: always
    depends_on:
      db_app:
        condition: service_healthy
  db_app:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: techforb_db
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10